---
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: "/:year/:month/:day/:title/"
excerpt_separator: ''
# gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-59760590-1
repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help
sass:
  style: compressed
